locale = "en_US"
url = "https://okubrowser.github.io"
# url = "http://localhost" # For developing locally
title = "Oku"
description = "Your home on the Internet"
author = "Emil Sayahi"
browser_repository = "https://github.com/OkuBrowser/oku"
protocol_repository = "https://github.com/OkuBrowser/oku-fs"
sponsor_link = "https://github.com/sponsors/emmyoh"